name: Deploy Vite to GitHub Pages

on:
  push:
    branches:
      - main # Cambia "main" si usas otro branch como predeterminado

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js 22
      uses: actions/setup-node@v3
      with:
        node-version: 20 # Versión estable actual de Node.js
        cache: 'yarn'

    - name: Install dependencies with Yarn
      run: yarn install

    - name: Build project
      run: yarn build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
