name: Deploy Vite to GitHub Pages

on:
  push:
    branches:
      - main # Cambia "main" si usas otro branch como predeterminado

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Descargar el c칩digo fuente
      - uses: actions/checkout@v4

      # Paso 2: Configurar Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 22 # Usamos la versi칩n m치s reciente compatible

      # Paso 3: Instalar dependencias con Yarn
      - run: yarn install

      # Paso 4: Construir el proyecto
      - run: yarn build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      # Paso 1: Descargar el c칩digo fuente nuevamente
      - uses: actions/checkout@v4

      # Paso 2: Configurar Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      # Paso 3: Instalar dependencias con Yarn
      - run: yarn install

      # Paso 4: Deploy a GitHub Pages
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
